# Generated by Django 4.2.2 on 2023-06-06 09:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_description_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
